export const glossaryCategories = [
  'すべて',
  '基本',
  'プリフロップ',
  'ポストフロップ',
  '数理・理論',
  'トーナメント',
  'メンタル・資金管理',
] as const;

export type GlossaryCategory = typeof glossaryCategories[number];

export type GlossaryTerm = {
  slug: string;
  term: string;
  reading: string;
  category: Exclude<GlossaryCategory, 'すべて'>;
  definition: string;
  relatedTags: string[];
  searchQuery: string;
};

export const glossaryTerms: GlossaryTerm[] = [
  {
    slug: 'equity',
    term: 'エクイティ',
    reading: 'えくいてぃ',
    category: '数理・理論',
    definition: '現在のハンドやレンジが、最終的にポットを獲得する確率。相手のレンジとの比較で考えます。',
    relatedTags: ['GTO', 'レンジ'],
    searchQuery: 'equity',
  },
  {
    slug: 'odds',
    term: 'オッズ',
    reading: 'おっず',
    category: '基本',
    definition: 'ある結果が起こる確率と、得られるリターンの比率。ポーカーではコールの判断材料になります。',
    relatedTags: ['ポットオッズ', 'EV'],
    searchQuery: 'odds',
  },
  {
    slug: 'open-raise',
    term: 'オープンレイズ',
    reading: 'おーぷんれいず',
    category: 'プリフロップ',
    definition: '誰も参加していない状態で、最初にレイズしてポットへ参加することです。',
    relatedTags: ['プリフロップ', 'レンジ'],
    searchQuery: 'open raise',
  },
  {
    slug: 'outs',
    term: 'アウト',
    reading: 'あうと',
    category: 'ポストフロップ',
    definition: 'ドローなどを完成させ、勝てるハンドへ改善する残りのカード。相手のハンドによって有効性が変わります。',
    relatedTags: ['ドロー', 'エクイティ'],
    searchQuery: 'outs',
  },
  {
    slug: 'ante',
    term: 'アンティ',
    reading: 'あんてぃ',
    category: '基本',
    definition: 'ハンド開始前に、全員または一部のプレイヤーが支払う強制ベット。ポットの大きさと参加インセンティブに影響します。',
    relatedTags: ['プリフロップ', 'トーナメント'],
    searchQuery: 'ante',
  },
  {
    slug: 'icm',
    term: 'ICM',
    reading: 'あいしーえむ',
    category: 'トーナメント',
    definition: 'トーナメントチップを賞金の期待値へ変換して考えるモデル。賞金差がある終盤の判断で重要になります。',
    relatedTags: ['MTT', 'トーナメント'],
    searchQuery: 'ICM',
  },
  {
    slug: 'ev',
    term: 'EV（期待値）',
    reading: 'いーぶい',
    category: '数理・理論',
    definition: '同じ判断を長期的に繰り返したとき、平均してどれだけ利益が見込めるかを表す値です。',
    relatedTags: ['GTO', '意思決定'],
    searchQuery: 'expected value',
  },
  {
    slug: 'indifference',
    term: 'インディファレンス',
    reading: 'いんでぃふぁれんす',
    category: '数理・理論',
    definition: '複数のアクションのEVが等しく、相手がどの選択をしても大きな差が生まれない状態です。',
    relatedTags: ['GTO', 'EV'],
    searchQuery: 'indifference',
  },
  {
    slug: 'range',
    term: 'レンジ',
    reading: 'れんじ',
    category: '基本',
    definition: 'ある状況でプレイヤーが持ちうるハンドの組み合わせ全体。1つのハンドではなく、分布として戦略を考えます。',
    relatedTags: ['GTO', 'プリフロップ'],
    searchQuery: 'range',
  },
  {
    slug: 'position',
    term: 'ポジション',
    reading: 'ぽじしょん',
    category: '基本',
    definition: 'ポットに対して行動する順番。後から行動できるほど情報が増えるため、一般に有利になります。',
    relatedTags: ['プリフロップ', 'ポストフロップ'],
    searchQuery: 'position',
  },
  {
    slug: 'pot-odds',
    term: 'ポットオッズ',
    reading: 'ぽっとおっず',
    category: '数理・理論',
    definition: 'コールに必要な投資額と、コール後に獲得できるポットの比率。必要エクイティとの比較に使います。',
    relatedTags: ['オッズ', 'EV'],
    searchQuery: 'pot odds',
  },
  {
    slug: 'spr',
    term: 'SPR',
    reading: 'えすぴーあーる',
    category: '数理・理論',
    definition: 'スタックとポットの比率。SPRが低いほど、強いワンペアなどでも大きなポットを戦いやすくなります。',
    relatedTags: ['ポストフロップ', 'スタック'],
    searchQuery: 'SPR',
  },
  {
    slug: 'three-bet',
    term: '3ベット',
    reading: 'すりーべっと',
    category: 'プリフロップ',
    definition: 'プリフロップで、オープンレイズに対して行うリレイズ。バリューとブラフの組み合わせでレンジを作ります。',
    relatedTags: ['プリフロップ', 'GTO'],
    searchQuery: '3bet',
  },
  {
    slug: 'four-bet',
    term: '4ベット',
    reading: 'ふぉーべっと',
    category: 'プリフロップ',
    definition: '3ベットに対して行う、さらにもう一段階のレイズ。スタック深さと相手のレンジが判断の鍵になります。',
    relatedTags: ['プリフロップ', 'GTO'],
    searchQuery: '4bet',
  },
  {
    slug: 'squeeze',
    term: 'スクイーズ',
    reading: 'すくいーず',
    category: 'プリフロップ',
    definition: 'オープンレイズとコールが入ったあとに、後ろから大きくレイズして圧力をかけるプレイです。',
    relatedTags: ['プリフロップ', 'エクスプロイト'],
    searchQuery: 'squeeze',
  },
  {
    slug: 'limp',
    term: 'リンプ',
    reading: 'りんぷ',
    category: 'プリフロップ',
    definition: 'プリフロップでレイズせず、ビッグブラインドと同額を支払って参加することです。',
    relatedTags: ['プリフロップ', 'レンジ'],
    searchQuery: 'limp',
  },
  {
    slug: 'c-bet',
    term: 'Cベット',
    reading: 'しーべっと',
    category: 'ポストフロップ',
    definition: 'プリフロップで最後にレイズしたプレイヤーが、フロップでも続けて行うベットです。',
    relatedTags: ['フロップ', 'GTO'],
    searchQuery: 'c-bet',
  },
  {
    slug: 'donk-bet',
    term: 'ドンクベット',
    reading: 'どんくべっと',
    category: 'ポストフロップ',
    definition: '前のストリートで最後にアグレッサーでなかったプレイヤーが、次のストリートで先に行うベットです。',
    relatedTags: ['フロップ', 'ターン'],
    searchQuery: 'donk',
  },
  {
    slug: 'barrel',
    term: 'バレル',
    reading: 'ばれる',
    category: 'ポストフロップ',
    definition: '前のストリートから続けてベットすること。ターンでの2ndバレル、リバーでの3rdバレルなどがあります。',
    relatedTags: ['ターン', 'リバー'],
    searchQuery: 'barrel',
  },
  {
    slug: 'backdoor-draw',
    term: 'バックドアドロー',
    reading: 'ばっくどあどろー',
    category: 'ポストフロップ',
    definition: 'ターンとリバーの両方で都合のよいカードが必要なドロー。フロップ後の2枚のカードで完成を目指します。',
    relatedTags: ['フロップ', 'ドロー'],
    searchQuery: 'backdoor',
  },
  {
    slug: 'blocker',
    term: 'ブロッカー',
    reading: 'ぶろっかー',
    category: '数理・理論',
    definition: '自分の手札が、相手が持ちうる特定のハンドの組み合わせ数を減らす効果。ブラフやバリュー判断に影響します。',
    relatedTags: ['レンジ', 'ブラフ'],
    searchQuery: 'blocker',
  },
  {
    slug: 'combo',
    term: 'コンボ',
    reading: 'こんぼ',
    category: '数理・理論',
    definition: '特定のハンドを作るカードの組み合わせ数。レンジの重み付けやブロッカーの分析に使います。',
    relatedTags: ['レンジ', 'ブロッカー'],
    searchQuery: 'combinatorics',
  },
  {
    slug: 'mdf',
    term: 'MDF',
    reading: 'えむでぃーえふ',
    category: '数理・理論',
    definition: 'Minimum Defense Frequencyの略。相手のベットに対して、理論上どの程度の頻度で守る必要があるかを示します。',
    relatedTags: ['GTO', 'ディフェンス'],
    searchQuery: 'MDF',
  },
  {
    slug: 'exploit',
    term: 'エクスプロイト',
    reading: 'えくすぷろいと',
    category: '数理・理論',
    definition: '相手の傾向やミスに合わせて、均衡戦略から意図的に調整して利益を取りにいくことです。',
    relatedTags: ['GTO', '相手別調整'],
    searchQuery: 'exploit',
  },
  {
    slug: 'chip-ev',
    term: 'チップEV',
    reading: 'ちっぷいーぶい',
    category: 'トーナメント',
    definition: '賞金ではなく、チップ量そのものの増減を基準にした期待値。トーナメント序盤などで使われます。',
    relatedTags: ['MTT', 'ICM'],
    searchQuery: 'chip EV',
  },
  {
    slug: 'bubble',
    term: 'バブル',
    reading: 'ばぶる',
    category: 'トーナメント',
    definition: 'あと少しで入賞者が確定する、賞金の境目にいる状況。ICMの影響が特に大きくなります。',
    relatedTags: ['MTT', 'ICM'],
    searchQuery: 'bubble',
  },
  {
    slug: 'pko',
    term: 'PKO',
    reading: 'ぴーけーおー',
    category: 'トーナメント',
    definition: 'Progressive Knockoutの略。相手を飛ばしたときのバウンティが、次の賞金へ積み上がる形式のトーナメントです。',
    relatedTags: ['MTT', 'バウンティ'],
    searchQuery: 'PKO',
  },
  {
    slug: 'bankroll-management',
    term: 'バンクロール管理',
    reading: 'ばんくろーるかんり',
    category: 'メンタル・資金管理',
    definition: 'ポーカーに使う資金を生活資金と分け、分散やダウンスイングに耐えられる範囲で参加額を管理することです。',
    relatedTags: ['バンクロール', 'リスク管理'],
    searchQuery: 'bankroll',
  },
  {
    slug: 'tilt',
    term: 'ティルト',
    reading: 'てぃると',
    category: 'メンタル・資金管理',
    definition: '感情の乱れによって、普段より悪い判断や衝動的なプレイをしてしまう状態です。',
    relatedTags: ['メンタル', '意思決定'],
    searchQuery: 'tilt',
  },
  {
    slug: 'variance',
    term: '分散',
    reading: 'ぶんさん',
    category: 'メンタル・資金管理',
    definition: '長期的な期待値の周りで、短期の結果が上下する幅。正しい判断をしていても結果がぶれる理由の一つです。',
    relatedTags: ['バンクロール', 'EV'],
    searchQuery: 'variance',
  },
];
