export const glossaryCategories = [
  'すべて',
  '基本',
  'プリフロップ',
  'ポストフロップ',
  '数理・理論',
  'トーナメント',
  'メンタル・資金管理',
] as const;

export type GlossaryCategory = typeof glossaryCategories[number];

export type GlossaryTerm = {
  slug: string;
  term: string;
  reading: string;
  category: Exclude<GlossaryCategory, 'すべて'>;
  definition: string;
  relatedTags: string[];
  searchQuery: string;
};

export const glossaryTerms: GlossaryTerm[] = [
  {
    slug: 'equity',
    term: 'エクイティ',
    reading: 'えくいてぃ',
    category: '数理・理論',
    definition: '現在のハンドやレンジが、最終的にポットを獲得する確率。相手のレンジとの比較で考えます。',
    relatedTags: ['GTO', 'レンジ'],
    searchQuery: 'equity',
  },
  {
    slug: 'odds',
    term: 'オッズ',
    reading: 'おっず',
    category: '基本',
    definition: 'ある結果が起こる確率と、得られるリターンの比率。ポーカーではコールの判断材料になります。',
    relatedTags: ['ポットオッズ', 'EV'],
    searchQuery: 'odds',
  },
  {
    slug: 'open-raise',
    term: 'オープンレイズ',
    reading: 'おーぷんれいず',
    category: 'プリフロップ',
    definition: '誰も参加していない状態で、最初にレイズしてポットへ参加することです。',
    relatedTags: ['プリフロップ', 'レンジ'],
    searchQuery: 'open raise',
  },
  {
    slug: 'outs',
    term: 'アウト',
    reading: 'あうと',
    category: 'ポストフロップ',
    definition: 'ドローなどを完成させ、勝てるハンドへ改善する残りのカード。相手のハンドによって有効性が変わります。',
    relatedTags: ['ドロー', 'エクイティ'],
    searchQuery: 'outs',
  },
  {
    slug: 'ante',
    term: 'アンティ',
    reading: 'あんてぃ',
    category: '基本',
    definition: 'ハンド開始前に、全員または一部のプレイヤーが支払う強制ベット。ポットの大きさと参加インセンティブに影響します。',
    relatedTags: ['プリフロップ', 'トーナメント'],
    searchQuery: 'ante',
  },
  {
    slug: 'icm',
    term: 'ICM',
    reading: 'あいしーえむ',
    category: 'トーナメント',
    definition: 'トーナメントチップを賞金の期待値へ変換して考えるモデル。賞金差がある終盤の判断で重要になります。',
    relatedTags: ['MTT', 'トーナメント'],
    searchQuery: 'ICM',
  },
  {
    slug: 'ev',
    term: 'EV（期待値）',
    reading: 'いーぶい',
    category: '数理・理論',
    definition: '同じ判断を長期的に繰り返したとき、平均してどれだけ利益が見込めるかを表す値です。',
    relatedTags: ['GTO', '意思決定'],
    searchQuery: 'expected value',
  },
  {
    slug: 'indifference',
    term: 'インディファレンス',
    reading: 'いんでぃふぁれんす',
    category: '数理・理論',
    definition: '複数のアクションのEVが等しく、相手がどの選択をしても大きな差が生まれない状態です。',
    relatedTags: ['GTO', 'EV'],
    searchQuery: 'indifference',
  },
  {
    slug: 'range',
    term: 'レンジ',
    reading: 'れんじ',
    category: '基本',
    definition: 'ある状況でプレイヤーが持ちうるハンドの組み合わせ全体。1つのハンドではなく、分布として戦略を考えます。',
    relatedTags: ['GTO', 'プリフロップ'],
    searchQuery: 'range',
  },
  {
    slug: 'position',
    term: 'ポジション',
    reading: 'ぽじしょん',
    category: '基本',
    definition: 'ポットに対して行動する順番。後から行動できるほど情報が増えるため、一般に有利になります。',
    relatedTags: ['プリフロップ', 'ポストフロップ'],
    searchQuery: 'position',
  },
  {
    slug: 'pot-odds',
    term: 'ポットオッズ',
    reading: 'ぽっとおっず',
    category: '数理・理論',
    definition: 'コールに必要な投資額と、コール後に獲得できるポットの比率。必要エクイティとの比較に使います。',
    relatedTags: ['オッズ', 'EV'],
    searchQuery: 'pot odds',
  },
  {
    slug: 'spr',
    term: 'SPR',
    reading: 'えすぴーあーる',
    category: '数理・理論',
    definition: 'スタックとポットの比率。SPRが低いほど、強いワンペアなどでも大きなポットを戦いやすくなります。',
    relatedTags: ['ポストフロップ', 'スタック'],
    searchQuery: 'SPR',
  },
  {
    slug: 'three-bet',
    term: '3ベット',
    reading: 'すりーべっと',
    category: 'プリフロップ',
    definition: 'プリフロップで、オープンレイズに対して行うリレイズ。バリューとブラフの組み合わせでレンジを作ります。',
    relatedTags: ['プリフロップ', 'GTO'],
    searchQuery: '3bet',
  },
  {
    slug: 'four-bet',
    term: '4ベット',
    reading: 'ふぉーべっと',
    category: 'プリフロップ',
    definition: '3ベットに対して行う、さらにもう一段階のレイズ。スタック深さと相手のレンジが判断の鍵になります。',
    relatedTags: ['プリフロップ', 'GTO'],
    searchQuery: '4bet',
  },
  {
    slug: 'squeeze',
    term: 'スクイーズ',
    reading: 'すくいーず',
    category: 'プリフロップ',
    definition: 'オープンレイズとコールが入ったあとに、後ろから大きくレイズして圧力をかけるプレイです。',
    relatedTags: ['プリフロップ', 'エクスプロイト'],
    searchQuery: 'squeeze',
  },
  {
    slug: 'limp',
    term: 'リンプ',
    reading: 'りんぷ',
    category: 'プリフロップ',
    definition: 'プリフロップでレイズせず、ビッグブラインドと同額を支払って参加することです。',
    relatedTags: ['プリフロップ', 'レンジ'],
    searchQuery: 'limp',
  },
  {
    slug: 'c-bet',
    term: 'Cベット',
    reading: 'しーべっと',
    category: 'ポストフロップ',
    definition: 'プリフロップで最後にレイズしたプレイヤーが、フロップでも続けて行うベットです。',
    relatedTags: ['フロップ', 'GTO'],
    searchQuery: 'c-bet',
  },
  {
    slug: 'donk-bet',
    term: 'ドンクベット',
    reading: 'どんくべっと',
    category: 'ポストフロップ',
    definition: '前のストリートで最後にアグレッサーでなかったプレイヤーが、次のストリートで先に行うベットです。',
    relatedTags: ['フロップ', 'ターン'],
    searchQuery: 'donk',
  },
  {
    slug: 'barrel',
    term: 'バレル',
    reading: 'ばれる',
    category: 'ポストフロップ',
    definition: '前のストリートから続けてベットすること。ターンでの2ndバレル、リバーでの3rdバレルなどがあります。',
    relatedTags: ['ターン', 'リバー'],
    searchQuery: 'barrel',
  },
  {
    slug: 'backdoor-draw',
    term: 'バックドアドロー',
    reading: 'ばっくどあどろー',
    category: 'ポストフロップ',
    definition: 'ターンとリバーの両方で都合のよいカードが必要なドロー。フロップ後の2枚のカードで完成を目指します。',
    relatedTags: ['フロップ', 'ドロー'],
    searchQuery: 'backdoor',
  },
  {
    slug: 'blocker',
    term: 'ブロッカー',
    reading: 'ぶろっかー',
    category: '数理・理論',
    definition: '自分の手札が、相手が持ちうる特定のハンドの組み合わせ数を減らす効果。ブラフやバリュー判断に影響します。',
    relatedTags: ['レンジ', 'ブラフ'],
    searchQuery: 'blocker',
  },
  {
    slug: 'combo',
    term: 'コンボ',
    reading: 'こんぼ',
    category: '数理・理論',
    definition: '特定のハンドを作るカードの組み合わせ数。レンジの重み付けやブロッカーの分析に使います。',
    relatedTags: ['レンジ', 'ブロッカー'],
    searchQuery: 'combinatorics',
  },
  {
    slug: 'mdf',
    term: 'MDF',
    reading: 'えむでぃーえふ',
    category: '数理・理論',
    definition: 'Minimum Defense Frequencyの略。相手のベットに対して、理論上どの程度の頻度で守る必要があるかを示します。',
    relatedTags: ['GTO', 'ディフェンス'],
    searchQuery: 'MDF',
  },
  {
    slug: 'exploit',
    term: 'エクスプロイト',
    reading: 'えくすぷろいと',
    category: '数理・理論',
    definition: '相手の傾向やミスに合わせて、均衡戦略から意図的に調整して利益を取りにいくことです。',
    relatedTags: ['GTO', '相手別調整'],
    searchQuery: 'exploit',
  },
  {
    slug: 'chip-ev',
    term: 'チップEV',
    reading: 'ちっぷいーぶい',
    category: 'トーナメント',
    definition: '賞金ではなく、チップ量そのものの増減を基準にした期待値。トーナメント序盤などで使われます。',
    relatedTags: ['MTT', 'ICM'],
    searchQuery: 'chip EV',
  },
  {
    slug: 'bubble',
    term: 'バブル',
    reading: 'ばぶる',
    category: 'トーナメント',
    definition: 'あと少しで入賞者が確定する、賞金の境目にいる状況。ICMの影響が特に大きくなります。',
    relatedTags: ['MTT', 'ICM'],
    searchQuery: 'bubble',
  },
  {
    slug: 'pko',
    term: 'PKO',
    reading: 'ぴーけーおー',
    category: 'トーナメント',
    definition: 'Progressive Knockoutの略。相手を飛ばしたときのバウンティが、次の賞金へ積み上がる形式のトーナメントです。',
    relatedTags: ['MTT', 'バウンティ'],
    searchQuery: 'PKO',
  },
  {
    slug: 'bankroll-management',
    term: 'バンクロール管理',
    reading: 'ばんくろーるかんり',
    category: 'メンタル・資金管理',
    definition: 'ポーカーに使う資金を生活資金と分け、分散やダウンスイングに耐えられる範囲で参加額を管理することです。',
    relatedTags: ['バンクロール', 'リスク管理'],
    searchQuery: 'bankroll',
  },
  {
    slug: 'tilt',
    term: 'ティルト',
    reading: 'てぃると',
    category: 'メンタル・資金管理',
    definition: '感情の乱れによって、普段より悪い判断や衝動的なプレイをしてしまう状態です。',
    relatedTags: ['メンタル', '意思決定'],
    searchQuery: 'tilt',
  },
  {
    slug: 'variance',
    term: '分散',
    reading: 'ぶんさん',
    category: 'メンタル・資金管理',
    definition: '長期的な期待値の周りで、短期の結果が上下する幅。正しい判断をしていても結果がぶれる理由の一つです。',
    relatedTags: ['バンクロール', 'EV'],
    searchQuery: 'variance',
  },
  {
    slug: 'blind',
    term: 'ブラインド',
    reading: 'ぶらいんど',
    category: '基本',
    definition: 'ハンド開始前にSBとBBが支払う強制ベット。ポットを生み、プレイを動かす起点になります。',
    relatedTags: ['プリフロップ', 'ポジション'],
    searchQuery: 'blind',
  },
  {
    slug: 'button',
    term: 'ボタン（BTN）',
    reading: 'ぼたん',
    category: '基本',
    definition: 'ディーラーの位置を示すポジション。ポストフロップで最後に行動できるため、最も有利な席です。',
    relatedTags: ['ポジション', 'スティール'],
    searchQuery: 'button',
  },
  {
    slug: 'cutoff',
    term: 'カットオフ（CO）',
    reading: 'かっとおふ',
    category: '基本',
    definition: 'ボタンのひとつ右の席。後ろのポジションで、広いレンジでオープンしやすい席です。',
    relatedTags: ['ポジション', 'オープンレイズ'],
    searchQuery: 'cutoff',
  },
  {
    slug: 'utg',
    term: 'UTG',
    reading: 'あんだーざがん',
    category: '基本',
    definition: 'プリフロップで最初に行動する席。後ろに多くのプレイヤーが残るため、タイトなレンジが基本です。',
    relatedTags: ['ポジション', 'レンジ'],
    searchQuery: 'UTG',
  },
  {
    slug: 'in-position',
    term: 'インポジション（IP）',
    reading: 'いんぽじしょん',
    category: '基本',
    definition: 'ポストフロップで相手より後に行動できる状態。情報面で有利に立てます。',
    relatedTags: ['ポジション', 'ポストフロップ'],
    searchQuery: 'in position',
  },
  {
    slug: 'out-of-position',
    term: 'アウトオブポジション（OOP）',
    reading: 'あうとおぶぽじしょん',
    category: '基本',
    definition: 'ポストフロップで相手より先に行動しなければならない状態。実現できるエクイティが下がりやすくなります。',
    relatedTags: ['ポジション', 'エクイティ'],
    searchQuery: 'out of position',
  },
  {
    slug: 'check-raise',
    term: 'チェックレイズ',
    reading: 'ちぇっくれいず',
    category: 'ポストフロップ',
    definition: '一度チェックしてから、相手のベットに対してレイズする行動。バリューとブラフの両方で使います。',
    relatedTags: ['OOP', 'ポストフロップ'],
    searchQuery: 'check raise',
  },
  {
    slug: 'check-behind',
    term: 'チェックバック',
    reading: 'ちぇっくばっく',
    category: 'ポストフロップ',
    definition: '最後に行動するプレイヤーがベットせずチェックで回すこと。ポットコントロールやショーダウン価値の確保に使います。',
    relatedTags: ['IP', 'ポットコントロール'],
    searchQuery: 'check back',
  },
  {
    slug: 'probe-bet',
    term: 'プローブベット',
    reading: 'ぷろーぶべっと',
    category: 'ポストフロップ',
    definition: '前のストリートでIPがチェックバックした後に、OOPがターンなどで先にベットすることです。',
    relatedTags: ['OOP', 'ターン'],
    searchQuery: 'probe bet',
  },
  {
    slug: 'float',
    term: 'フロート',
    reading: 'ふろーと',
    category: 'ポストフロップ',
    definition: '後のストリートで奪う意図を持って、弱いハンドでベットにコールすること。主にIPで使います。',
    relatedTags: ['IP', 'ブラフ'],
    searchQuery: 'float',
  },
  {
    slug: 'overbet',
    term: 'オーバーベット',
    reading: 'おーばーべっと',
    category: 'ポストフロップ',
    definition: 'ポットより大きい額をベットすること。レンジの優位が大きい場面で強く使われます。',
    relatedTags: ['ベットサイズ', 'ナッツアドバンテージ'],
    searchQuery: 'overbet',
  },
  {
    slug: 'block-bet',
    term: 'ブロックベット',
    reading: 'ぶろっくべっと',
    category: 'ポストフロップ',
    definition: 'OOPが小さく先にベットし、相手の大きなベットを防いで安くショーダウンを目指す行動です。',
    relatedTags: ['OOP', 'ベットサイズ'],
    searchQuery: 'block bet',
  },
  {
    slug: 'value-bet',
    term: 'バリューベット',
    reading: 'ばりゅーべっと',
    category: 'ポストフロップ',
    definition: 'より弱いハンドからコールをもらう目的のベット。勝っている時に利益を最大化します。',
    relatedTags: ['EV', 'シンバリュー'],
    searchQuery: 'value bet',
  },
  {
    slug: 'thin-value',
    term: 'シンバリュー',
    reading: 'しんばりゅー',
    category: 'ポストフロップ',
    definition: 'わずかに勝っている程度のハンドで取るバリューベット。相手のコールレンジを正確に読む力が必要です。',
    relatedTags: ['バリューベット', 'リバー'],
    searchQuery: 'thin value',
  },
  {
    slug: 'bluff',
    term: 'ブラフ',
    reading: 'ぶらふ',
    category: 'ポストフロップ',
    definition: '弱いハンドでベットやレイズを行い、相手に強いハンドを降ろさせることを狙う行動です。',
    relatedTags: ['フォールドエクイティ', 'ブロッカー'],
    searchQuery: 'bluff',
  },
  {
    slug: 'semi-bluff',
    term: 'セミブラフ',
    reading: 'せみぶらふ',
    category: 'ポストフロップ',
    definition: '現時点では弱いが、改善の見込みがあるドローでベットすること。降ろせる利益と完成時の利益の両方があります。',
    relatedTags: ['ドロー', 'アウト'],
    searchQuery: 'semi bluff',
  },
  {
    slug: 'draw',
    term: 'ドロー',
    reading: 'どろー',
    category: 'ポストフロップ',
    definition: 'あと一枚などでフラッシュやストレートが完成する未完成のハンドです。',
    relatedTags: ['アウト', 'セミブラフ'],
    searchQuery: 'draw',
  },
  {
    slug: 'flush-draw',
    term: 'フラッシュドロー',
    reading: 'ふらっしゅどろー',
    category: 'ポストフロップ',
    definition: '同じスートがあと一枚でフラッシュになる状態。フロップでは通常9枚のアウトがあります。',
    relatedTags: ['ドロー', 'アウト'],
    searchQuery: 'flush draw',
  },
  {
    slug: 'oesd',
    term: 'オープンエンドストレートドロー',
    reading: 'おーぷんえんど',
    category: 'ポストフロップ',
    definition: '両端のどちらかが来ればストレートになるドロー。通常8枚のアウトがあります。',
    relatedTags: ['ドロー', 'アウト'],
    searchQuery: 'open ended straight draw',
  },
  {
    slug: 'gutshot',
    term: 'ガットショット',
    reading: 'がっとしょっと',
    category: 'ポストフロップ',
    definition: '内側の特定の1ランクだけでストレートになるドロー。アウトは通常4枚です。',
    relatedTags: ['ドロー', 'アウト'],
    searchQuery: 'gutshot',
  },
  {
    slug: 'set',
    term: 'セット',
    reading: 'せっと',
    category: 'ポストフロップ',
    definition: 'ポケットペアとボードの1枚でスリーカードになること。隠れやすく強いハンドです。',
    relatedTags: ['ポケットペア', 'バリューベット'],
    searchQuery: 'set',
  },
  {
    slug: 'top-pair',
    term: 'トップペア',
    reading: 'とっぷぺあ',
    category: 'ポストフロップ',
    definition: 'ボードで一番高いカードとペアになったハンド。キッカーの強さで価値が変わります。',
    relatedTags: ['キッカー', 'バリューベット'],
    searchQuery: 'top pair',
  },
  {
    slug: 'kicker',
    term: 'キッカー',
    reading: 'きっかー',
    category: '基本',
    definition: '役が同じ時に勝敗を決める、役に使われていない残りのカードです。',
    relatedTags: ['トップペア', 'ドミネート'],
    searchQuery: 'kicker',
  },
  {
    slug: 'nuts',
    term: 'ナッツ',
    reading: 'なっつ',
    category: 'ポストフロップ',
    definition: 'その時点のボードで考えうる最強のハンドです。',
    relatedTags: ['ナッツアドバンテージ', 'バリューベット'],
    searchQuery: 'nuts',
  },
  {
    slug: 'board-texture',
    term: 'ボードテクスチャ',
    reading: 'ぼーどてくすちゃ',
    category: 'ポストフロップ',
    definition: 'ボードのカード構成。ドライかウェットかで、ベット頻度やサイズの選び方が大きく変わります。',
    relatedTags: ['Cベット', 'レンジアドバンテージ'],
    searchQuery: 'board texture',
  },
  {
    slug: 'range-advantage',
    term: 'レンジアドバンテージ',
    reading: 'れんじあどばんてーじ',
    category: '数理・理論',
    definition: 'あるボードで、自分のレンジ全体のエクイティが相手より高い状態。高頻度ベットの根拠になります。',
    relatedTags: ['レンジ', 'Cベット'],
    searchQuery: 'range advantage',
  },
  {
    slug: 'nut-advantage',
    term: 'ナッツアドバンテージ',
    reading: 'なっつあどばんてーじ',
    category: '数理・理論',
    definition: '最強クラスのハンドを相手より多く持っている状態。大きなベットやオーバーベットの根拠になります。',
    relatedTags: ['オーバーベット', 'ナッツ'],
    searchQuery: 'nut advantage',
  },
  {
    slug: 'polarized',
    term: 'ポラライズ',
    reading: 'ぽららいず',
    category: '数理・理論',
    definition: '強いハンドとブラフに二極化したレンジ。大きなベットサイズと相性が良い構成です。',
    relatedTags: ['レンジ', 'オーバーベット'],
    searchQuery: 'polarized range',
  },
  {
    slug: 'merged',
    term: 'マージ（リニア）',
    reading: 'まーじ',
    category: '数理・理論',
    definition: '強い順に上から連続して構成したレンジ。小さめのベットサイズと相性が良い構成です。',
    relatedTags: ['レンジ', 'ベットサイズ'],
    searchQuery: 'merged range',
  },
  {
    slug: 'capped',
    term: 'キャップされたレンジ',
    reading: 'きゃっぷ',
    category: '数理・理論',
    definition: 'これまでの行動から、最強クラスのハンドをほとんど含まないと読めるレンジです。',
    relatedTags: ['レンジ', 'オーバーベット'],
    searchQuery: 'capped range',
  },
  {
    slug: 'gto',
    term: 'GTO',
    reading: 'じーてぃーおー',
    category: '数理・理論',
    definition: '相手にエクスプロイトされにくい、理論上バランスの取れた戦略。ナッシュ均衡に基づく考え方です。',
    relatedTags: ['エクスプロイト', 'ソルバー'],
    searchQuery: 'GTO',
  },
  {
    slug: 'solver',
    term: 'ソルバー',
    reading: 'そるばー',
    category: '数理・理論',
    definition: '与えた条件のもとでGTOに近い戦略を計算するソフトウェア。学習や戦略検証に使われます。',
    relatedTags: ['GTO', 'レンジ'],
    searchQuery: 'solver',
  },
  {
    slug: 'mixed-strategy',
    term: '混合戦略',
    reading: 'こんごうせんりゃく',
    category: '数理・理論',
    definition: '同じハンドで複数のアクションを一定の頻度で使い分けること。相手に読まれにくくなります。',
    relatedTags: ['GTO', '頻度'],
    searchQuery: 'mixed strategy',
  },
  {
    slug: 'fold-equity',
    term: 'フォールドエクイティ',
    reading: 'ふぉーるどえくいてぃ',
    category: '数理・理論',
    definition: 'ベットやレイズで相手を降ろすことによって得られる期待値の部分です。',
    relatedTags: ['ブラフ', 'セミブラフ'],
    searchQuery: 'fold equity',
  },
  {
    slug: 'implied-odds',
    term: 'インプライドオッズ',
    reading: 'いんぷらいどおっず',
    category: '数理・理論',
    definition: 'ハンドが完成した後に、さらに獲得できると見込むチップまで含めたオッズです。',
    relatedTags: ['ポットオッズ', 'ドロー'],
    searchQuery: 'implied odds',
  },
  {
    slug: 'reverse-implied',
    term: 'リバースインプライドオッズ',
    reading: 'りばーすいんぷらいどおっず',
    category: '数理・理論',
    definition: 'ハンドが完成しても相手に負けていて、後のストリートで余計に失う見込みのことです。',
    relatedTags: ['インプライドオッズ', 'ドミネート'],
    searchQuery: 'reverse implied odds',
  },
  {
    slug: 'realization',
    term: 'エクイティリアライゼーション',
    reading: 'えくいてぃりありぜーしょん',
    category: '数理・理論',
    definition: '持っているエクイティを実際にどれだけ期待値として回収できるかの度合い。ポジションやハンドの操作性で変わります。',
    relatedTags: ['エクイティ', 'ポジション'],
    searchQuery: 'equity realization',
  },
  {
    slug: 'rule-of-4-2',
    term: '4と2のルール',
    reading: 'よんとにのるーる',
    category: '数理・理論',
    definition: 'アウトの数に、フロップでは4、ターンでは2を掛けて完成確率を概算する方法です。',
    relatedTags: ['アウト', 'ポットオッズ'],
    searchQuery: 'rule of 4 and 2',
  },
  {
    slug: 'dominated',
    term: 'ドミネート',
    reading: 'どみねーと',
    category: '数理・理論',
    definition: 'キッカー負けなどで、相手のハンドに大きく不利な状態。例としてAJに対するAKが挙げられます。',
    relatedTags: ['キッカー', 'リバースインプライドオッズ'],
    searchQuery: 'dominated',
  },
  {
    slug: 'steal',
    term: 'スティール',
    reading: 'すてぃーる',
    category: 'プリフロップ',
    definition: '後ろのポジションからオープンして、ブラインドを奪うことを狙うプレイです。',
    relatedTags: ['ボタン', 'ブラインド'],
    searchQuery: 'steal',
  },
  {
    slug: 'isolation',
    term: 'アイソレーション',
    reading: 'あいそれーしょん',
    category: 'プリフロップ',
    definition: 'リンプしたプレイヤーに対してレイズし、ヘッズアップに持ち込もうとするプレイです。',
    relatedTags: ['リンプ', 'ポジション'],
    searchQuery: 'isolation raise',
  },
  {
    slug: 'cold-call',
    term: 'コールドコール',
    reading: 'こーるどこーる',
    category: 'プリフロップ',
    definition: '自分がまだチップを入れていない状態で、他人のレイズにコールすることです。',
    relatedTags: ['3ベット', 'ポジション'],
    searchQuery: 'cold call',
  },
  {
    slug: 'flat',
    term: 'フラット',
    reading: 'ふらっと',
    category: 'プリフロップ',
    definition: 'レイズに対して、リレイズせずコールだけで応じることです。',
    relatedTags: ['コールドコール', '3ベット'],
    searchQuery: 'flat call',
  },
  {
    slug: 'pocket-pair',
    term: 'ポケットペア',
    reading: 'ぽけっとぺあ',
    category: 'プリフロップ',
    definition: '配られた2枚のホールカードがペアになっているハンドです。',
    relatedTags: ['セット', 'プリフロップ'],
    searchQuery: 'pocket pair',
  },
  {
    slug: 'suited-connector',
    term: 'スーテッドコネクター',
    reading: 'すーてっどこねくたー',
    category: 'プリフロップ',
    definition: '同じスートで連続したランクの2枚（例：87s）。ストレートとフラッシュの両方を狙えます。',
    relatedTags: ['ドロー', 'インプライドオッズ'],
    searchQuery: 'suited connectors',
  },
  {
    slug: 'open-shove',
    term: 'オープンシャブ',
    reading: 'おーぷんしゃぶ',
    category: 'トーナメント',
    definition: '誰も参加していない状態で、最初にオールインすること。ショートスタックの基本戦略です。',
    relatedTags: ['ショートスタック', 'プッシュ／フォールド'],
    searchQuery: 'open shove',
  },
  {
    slug: 'push-fold',
    term: 'プッシュ／フォールド',
    reading: 'ぷっしゅふぉーるど',
    category: 'トーナメント',
    definition: 'スタックが浅い時に、オールインかフォールドの二択でプレイする戦略です。',
    relatedTags: ['ショートスタック', 'ICM'],
    searchQuery: 'push fold',
  },
  {
    slug: 'reshove',
    term: 'リシャブ',
    reading: 'りしゃぶ',
    category: 'トーナメント',
    definition: '相手のオープンに対してオールインで返すこと。中程度のスタックでよく使われます。',
    relatedTags: ['3ベット', 'プッシュ／フォールド'],
    searchQuery: 'reshove',
  },
  {
    slug: 'bb-ante',
    term: 'BBアンティ',
    reading: 'びーびーあんてぃ',
    category: 'トーナメント',
    definition: 'ビッグブラインドの人が全員分のアンティをまとめて払う方式。多くのトーナメントで採用されています。',
    relatedTags: ['アンティ', 'ブラインド'],
    searchQuery: 'big blind ante',
  },
  {
    slug: 'itm',
    term: 'インザマネー（ITM）',
    reading: 'いんざまねー',
    category: 'トーナメント',
    definition: '賞金圏に入ること。バブルを越えた後の段階を指します。',
    relatedTags: ['バブル', 'ICM'],
    searchQuery: 'in the money',
  },
  {
    slug: 'final-table',
    term: 'ファイナルテーブル',
    reading: 'ふぁいなるてーぶる',
    category: 'トーナメント',
    definition: 'トーナメントの最終テーブル。賞金の差が大きく、ICMの影響が最も強くなります。',
    relatedTags: ['ICM', 'MTT'],
    searchQuery: 'final table',
  },
  {
    slug: 'risk-premium',
    term: 'リスクプレミアム',
    reading: 'りすくぷれみあむ',
    category: 'トーナメント',
    definition: 'ICMの影響で、チップEVよりも追加で必要になるエクイティの上乗せ分です。',
    relatedTags: ['ICM', 'バブル'],
    searchQuery: 'risk premium',
  },
  {
    slug: 'effective-stack',
    term: 'エフェクティブスタック',
    reading: 'えふぇくてぃぶすたっく',
    category: '基本',
    definition: '対戦するプレイヤーのうち、小さい方のスタック量。実際に賭けられる上限になります。',
    relatedTags: ['SPR', 'スタック'],
    searchQuery: 'effective stack',
  },
  {
    slug: 'showdown',
    term: 'ショーダウン',
    reading: 'しょーだうん',
    category: '基本',
    definition: '最終ストリートの後、残ったプレイヤーがハンドを見せて勝敗を決めることです。',
    relatedTags: ['リバー', 'バリューベット'],
    searchQuery: 'showdown',
  },
  {
    slug: 'street',
    term: 'ストリート',
    reading: 'すとりーと',
    category: '基本',
    definition: 'プリフロップ、フロップ、ターン、リバーなどのベッティングラウンドのことです。',
    relatedTags: ['ポストフロップ', 'バレル'],
    searchQuery: 'street',
  },
  {
    slug: 'hud',
    term: 'HUD',
    reading: 'はっど',
    category: 'メンタル・資金管理',
    definition: 'オンラインで相手のプレイ統計をテーブル上に表示するツール。VPIPやPFRなどを表示します。',
    relatedTags: ['VPIP', 'エクスプロイト'],
    searchQuery: 'HUD',
  },
  {
    slug: 'vpip',
    term: 'VPIP',
    reading: 'ぶいぴっぷ',
    category: '数理・理論',
    definition: 'プリフロップで自発的にポットへチップを入れた割合。プレイヤーのルーズさを示します。',
    relatedTags: ['PFR', 'HUD'],
    searchQuery: 'VPIP',
  },
  {
    slug: 'pfr',
    term: 'PFR',
    reading: 'ぴーえふあーる',
    category: '数理・理論',
    definition: 'プリフロップでレイズした割合。VPIPとの差からプレイスタイルを推定できます。',
    relatedTags: ['VPIP', 'HUD'],
    searchQuery: 'PFR',
  },
  {
    slug: 'bb-100',
    term: 'bb/100',
    reading: 'びーびーぱーひゃく',
    category: 'メンタル・資金管理',
    definition: '100ハンドあたりに勝ったビッグブラインドの数。キャッシュゲームの勝率指標です。',
    relatedTags: ['分散', 'バンクロール'],
    searchQuery: 'bb/100',
  },
  {
    slug: 'roi',
    term: 'ROI',
    reading: 'あーるおーあい',
    category: 'メンタル・資金管理',
    definition: 'トーナメントでのバイインに対する利益の割合。長期的な成績を測る指標です。',
    relatedTags: ['MTT', '分散'],
    searchQuery: 'ROI',
  },
  {
    slug: 'downswing',
    term: 'ダウンスイング',
    reading: 'だうんすいんぐ',
    category: 'メンタル・資金管理',
    definition: '分散によって一時的に負けが続く期間。資金管理とメンタルの安定が重要になります。',
    relatedTags: ['分散', 'ティルト'],
    searchQuery: 'downswing',
  },
  {
    slug: 'results-oriented',
    term: '結果論',
    reading: 'けっかろん',
    category: 'メンタル・資金管理',
    definition: '判断の良し悪しを短期の結果だけで評価してしまう思考の癖。改善の妨げになります。',
    relatedTags: ['分散', '意思決定'],
    searchQuery: 'results oriented',
  },
  {
    slug: 'table-selection',
    term: 'テーブル選択',
    reading: 'てーぶるせんたく',
    category: 'メンタル・資金管理',
    definition: '自分に有利な相手がいる卓を選ぶこと。勝率に大きく影響する実践的なスキルです。',
    relatedTags: ['エクスプロイト', 'bb/100'],
    searchQuery: 'table selection',
  },
];
